// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXxUJU25Q_zq7mxqk7KrHHY68xtr2khuY',
    appId: '1:27163669595:android:adf3d95f0f0ddf552dbb7e',
    messagingSenderId: '27163669595',
    projectId: 'edspert-course-8535d',
    storageBucket: 'edspert-course-8535d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSTZEp6OvnL8g3VrJBr1CYsQ5NiuK2DSI',
    appId: '1:27163669595:ios:fc17d2ff28bbd7e52dbb7e',
    messagingSenderId: '27163669595',
    projectId: 'edspert-course-8535d',
    storageBucket: 'edspert-course-8535d.appspot.com',
    androidClientId: '27163669595-hg1j15g2o4unh8j1kvvjr640h2hsdd9r.apps.googleusercontent.com',
    iosClientId: '27163669595-hp7jih2pv0s0a6gncfece41fnomlcd15.apps.googleusercontent.com',
    iosBundleId: 'com.alviazirin.edspertCourse',
  );

}